dist: trusty
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "lusitaniae-github"

cache:
  directories:
    - '$HOME/.sonar/cache'

before_install:
  - sudo service mysql stop

install:
  - docker-compose up --build -d
  # dummy way to ensure all services ready
  - sleep 30s
  - docker-compose exec app php artisan migrate --seed

script:
  - docker-compose exec app vendor/bin/phpunit
  
  - sonar-scanner \
    -Dsonar.projectKey=Lusitaniae_API-Exercise \
    -Dsonar.organization=lusitaniae-github \
    -Dsonar.sources=. \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN

  - > # run extensive load testing during nightly builds
      if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
          docker run --net=host -ii loadimpact/k6 run - <load_test.js
      fi
