sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop

install:
  - docker-compose up --build -d
  - docker-compose exec app php artisan migrate --seed

script:
  - docker-compose exec app vendor/bin/phpunit
