version: '2'
services:

  # The Application
  app:
    image: lusotycoon/app
    build:
      context: ./
      dockerfile: resources/docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      DB_HOST: database

  # Dependency Manager
  composer:
    image: composer
    working_dir: /var/www
    volumes_from:
      - app
    command: install --optimize-autoloader

  # The Web Server
  web:
    image: lusotycoon/web
    build:
      context: ./
      dockerfile: resources/docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    ports:
        - "33061:3306"

volumes:
  dbdata:
