version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: resources/docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # Dependency Manager
  composer:
    image: "composer"
    working_dir: /var/www
    volumes_from:
      - app
    command: install
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: resources/docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
    ports:
        - "33061:3306"

volumes:
  dbdata:
